services:
  client:
    image: ghcr.io/yassentials/game-tic-tac-toe/client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
  
  server:
    image: ghcr.io/yassentials/game-tic-tac-toe/server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
